export const SET_QUNIU_TOKEN = 'SET_QUNIU_TOKEN'

export const SET_SIDE_ROUTER = 'SET_SIDE_ROUTER'

export const SET_TOTAL_SUM = 'SET_TOTAL_SUM'

export const SET_PAGE_SIZE = 'SET_PAGE_SIZE'

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'

export const SET_TABEL_LOAD_INDEX = 'SET_TABEL_LOAD_INDEX'

export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_TABEL_LOAD_MODAL = 'SET_TABEL_LOAD_MODAL'

export const SET_TOTAL_SUM_MODAL = 'SET_TOTAL_SUM_MODAL'

export const SET_PAGE_SIZE_MODAL = 'SET_PAGE_SIZE_MODAL'

export const SET_CURRENT_PAGE_MODAL = 'SET_CURRENT_PAGE_MODAL'

